### ISSUE TITLE
Possible reference to the wrong queue? 🤔

### ISSUE THREAD

**Issue by pabloleonalcaide** [CodelyTV/php-ddd-skeleton#16]
https://github.com/CodelyTV/php-ddd-skeleton/blob/d67e903ddbc3f01d888bd636ea715387667aea32/src/Shared/Infrastructure/Bus/Event/RabbitMq/RabbitMqConfigurer.php#L64
https://github.com/CodelyTV/php-ddd-skeleton/blob/d67e903ddbc3f01d888bd636ea715387667aea32/src/Shared/Infrastructure/Bus/Event/RabbitMq/RabbitMqConfigurer.php#L78-L81

I've noticed that the arguments 'deadLetterExchange' and 'deadLetterRoutingKey' are being used only when the 'RetryQueue' is declared, so.. Maybe shoud be better called 'retryExchange' and 'retryRoutingkey' ?
Anyway I can be confused, that's why I only suggest in an issue! 😅

**Comment by rgomezcasas** [comment]
It make sense, but the confusion is for how RabbitMQ works. What we do understand for "retry" is the equivalent for "dead letter" to the RabbitMQ domain...

**Comment by pabloleonalcaide** [comment]
Ok! I understand now, thanks! 😃 
I'll close the issue so
