### ISSUE TITLE
Error autowire al instalar

### ISSUE THREAD

**Issue by danitome24** [CodelyTV/php-ddd-skeleton#4]
He hecho una instalación de nuevo del proyecto y a la hora de acceder a la url `http://localhost:8030` me muestra un error de autowire: 

<img width="1065" alt="Captura de pantalla 2019-08-17 a las 23 21 13" src="https://user-images.githubusercontent.com/7501990/63217372-c7c52100-c145-11e9-91c8-a8bd9248d5fb.png">

**Comment by JavierCane** [comment]
Uops!
Gracias por el reporte y mil disculpas por las molestias.

Mientras sacamos tiempo para echarle un ojo, puedes tirar de la versión "básica" con un `composer create-project codelytv/ddd-skeleton 0.4`

Así al menos podrás seguir [el curso de DDD en PHP](https://pro.codely.tv/library/ddd-en-php/96188/about/) sin bloquearte 😊

Saludos!

**Comment by rgomezcasas** [comment]
Esto estaba arreglado en la rama de la integración con RabbitMQ, lo he portado a master también para que no falle :) Ya debería de irte bien!

**Comment by danitome24** [comment]
Gracias!!! Molaría que la versión `0.4` se dejara en una rama (`base`) para poder usar estre proyecto como skeleton, incluyendo además, las clases básicas para DDD (agregado, domainEvent, etc.)

**Comment by rgomezcasas** [comment]
*Eventualmente* todo esto será configurable (después del `composer install` te preguntará qué namespace quieres tener y qué features habilitar)... Pero aún queda un poquito! 😅😊
